[test]
preload = ["./tests/setup.ts"]

[test.smelt]
root = "./tests"

[install]
registry = "https://registry.npmjs.org"

[install.scopes]
"@ninots" = { token = "$NPM_CONFIG_TOKEN", url = "https://registry.npmjs.org/" }
